version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: hanger_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./packages/server
    container_name: hanger_api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_SQL_INIT_MODE: always

  client:
    build:
      context: ./packages/client
      args:
        VITE_BUILD_COMMIT: ${VITE_BUILD_COMMIT:-unknown}
    container_name: hanger_client
    ports:
      - "5173:80" # Maps container port 80 to host port 5173
    depends_on:
      - server

volumes:
  db_data:
