spring.datasource.url=jdbc:postgresql://localhost:5432/hanger_db
spring.datasource.username=plane_commander
spring.datasource.password=hanger_1000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
